package org.vincent.dao.model;

import java.util.Date;

public class BatchStepExecution {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_STEP_EXECUTION.STEP_EXECUTION_ID
     *
     * @mbg.generated
     */
    private Long stepExecutionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_STEP_EXECUTION.VERSION
     *
     * @mbg.generated
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_STEP_EXECUTION.STEP_NAME
     *
     * @mbg.generated
     */
    private String stepName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_STEP_EXECUTION.JOB_EXECUTION_ID
     *
     * @mbg.generated
     */
    private Long jobExecutionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_STEP_EXECUTION.START_TIME
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_STEP_EXECUTION.END_TIME
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_STEP_EXECUTION.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_STEP_EXECUTION.COMMIT_COUNT
     *
     * @mbg.generated
     */
    private Long commitCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_STEP_EXECUTION.READ_COUNT
     *
     * @mbg.generated
     */
    private Long readCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_STEP_EXECUTION.FILTER_COUNT
     *
     * @mbg.generated
     */
    private Long filterCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_STEP_EXECUTION.WRITE_COUNT
     *
     * @mbg.generated
     */
    private Long writeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_STEP_EXECUTION.READ_SKIP_COUNT
     *
     * @mbg.generated
     */
    private Long readSkipCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_STEP_EXECUTION.WRITE_SKIP_COUNT
     *
     * @mbg.generated
     */
    private Long writeSkipCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_STEP_EXECUTION.PROCESS_SKIP_COUNT
     *
     * @mbg.generated
     */
    private Long processSkipCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_STEP_EXECUTION.ROLLBACK_COUNT
     *
     * @mbg.generated
     */
    private Long rollbackCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_STEP_EXECUTION.EXIT_CODE
     *
     * @mbg.generated
     */
    private String exitCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_STEP_EXECUTION.EXIT_MESSAGE
     *
     * @mbg.generated
     */
    private String exitMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_STEP_EXECUTION.LAST_UPDATED
     *
     * @mbg.generated
     */
    private Date lastUpdated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_STEP_EXECUTION.STEP_EXECUTION_ID
     *
     * @return the value of BATCH_STEP_EXECUTION.STEP_EXECUTION_ID
     *
     * @mbg.generated
     */
    public Long getStepExecutionId() {
        return stepExecutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_STEP_EXECUTION.STEP_EXECUTION_ID
     *
     * @param stepExecutionId the value for BATCH_STEP_EXECUTION.STEP_EXECUTION_ID
     *
     * @mbg.generated
     */
    public void setStepExecutionId(Long stepExecutionId) {
        this.stepExecutionId = stepExecutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_STEP_EXECUTION.VERSION
     *
     * @return the value of BATCH_STEP_EXECUTION.VERSION
     *
     * @mbg.generated
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_STEP_EXECUTION.VERSION
     *
     * @param version the value for BATCH_STEP_EXECUTION.VERSION
     *
     * @mbg.generated
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_STEP_EXECUTION.STEP_NAME
     *
     * @return the value of BATCH_STEP_EXECUTION.STEP_NAME
     *
     * @mbg.generated
     */
    public String getStepName() {
        return stepName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_STEP_EXECUTION.STEP_NAME
     *
     * @param stepName the value for BATCH_STEP_EXECUTION.STEP_NAME
     *
     * @mbg.generated
     */
    public void setStepName(String stepName) {
        this.stepName = stepName == null ? null : stepName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_STEP_EXECUTION.JOB_EXECUTION_ID
     *
     * @return the value of BATCH_STEP_EXECUTION.JOB_EXECUTION_ID
     *
     * @mbg.generated
     */
    public Long getJobExecutionId() {
        return jobExecutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_STEP_EXECUTION.JOB_EXECUTION_ID
     *
     * @param jobExecutionId the value for BATCH_STEP_EXECUTION.JOB_EXECUTION_ID
     *
     * @mbg.generated
     */
    public void setJobExecutionId(Long jobExecutionId) {
        this.jobExecutionId = jobExecutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_STEP_EXECUTION.START_TIME
     *
     * @return the value of BATCH_STEP_EXECUTION.START_TIME
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_STEP_EXECUTION.START_TIME
     *
     * @param startTime the value for BATCH_STEP_EXECUTION.START_TIME
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_STEP_EXECUTION.END_TIME
     *
     * @return the value of BATCH_STEP_EXECUTION.END_TIME
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_STEP_EXECUTION.END_TIME
     *
     * @param endTime the value for BATCH_STEP_EXECUTION.END_TIME
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_STEP_EXECUTION.STATUS
     *
     * @return the value of BATCH_STEP_EXECUTION.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_STEP_EXECUTION.STATUS
     *
     * @param status the value for BATCH_STEP_EXECUTION.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_STEP_EXECUTION.COMMIT_COUNT
     *
     * @return the value of BATCH_STEP_EXECUTION.COMMIT_COUNT
     *
     * @mbg.generated
     */
    public Long getCommitCount() {
        return commitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_STEP_EXECUTION.COMMIT_COUNT
     *
     * @param commitCount the value for BATCH_STEP_EXECUTION.COMMIT_COUNT
     *
     * @mbg.generated
     */
    public void setCommitCount(Long commitCount) {
        this.commitCount = commitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_STEP_EXECUTION.READ_COUNT
     *
     * @return the value of BATCH_STEP_EXECUTION.READ_COUNT
     *
     * @mbg.generated
     */
    public Long getReadCount() {
        return readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_STEP_EXECUTION.READ_COUNT
     *
     * @param readCount the value for BATCH_STEP_EXECUTION.READ_COUNT
     *
     * @mbg.generated
     */
    public void setReadCount(Long readCount) {
        this.readCount = readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_STEP_EXECUTION.FILTER_COUNT
     *
     * @return the value of BATCH_STEP_EXECUTION.FILTER_COUNT
     *
     * @mbg.generated
     */
    public Long getFilterCount() {
        return filterCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_STEP_EXECUTION.FILTER_COUNT
     *
     * @param filterCount the value for BATCH_STEP_EXECUTION.FILTER_COUNT
     *
     * @mbg.generated
     */
    public void setFilterCount(Long filterCount) {
        this.filterCount = filterCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_STEP_EXECUTION.WRITE_COUNT
     *
     * @return the value of BATCH_STEP_EXECUTION.WRITE_COUNT
     *
     * @mbg.generated
     */
    public Long getWriteCount() {
        return writeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_STEP_EXECUTION.WRITE_COUNT
     *
     * @param writeCount the value for BATCH_STEP_EXECUTION.WRITE_COUNT
     *
     * @mbg.generated
     */
    public void setWriteCount(Long writeCount) {
        this.writeCount = writeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_STEP_EXECUTION.READ_SKIP_COUNT
     *
     * @return the value of BATCH_STEP_EXECUTION.READ_SKIP_COUNT
     *
     * @mbg.generated
     */
    public Long getReadSkipCount() {
        return readSkipCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_STEP_EXECUTION.READ_SKIP_COUNT
     *
     * @param readSkipCount the value for BATCH_STEP_EXECUTION.READ_SKIP_COUNT
     *
     * @mbg.generated
     */
    public void setReadSkipCount(Long readSkipCount) {
        this.readSkipCount = readSkipCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_STEP_EXECUTION.WRITE_SKIP_COUNT
     *
     * @return the value of BATCH_STEP_EXECUTION.WRITE_SKIP_COUNT
     *
     * @mbg.generated
     */
    public Long getWriteSkipCount() {
        return writeSkipCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_STEP_EXECUTION.WRITE_SKIP_COUNT
     *
     * @param writeSkipCount the value for BATCH_STEP_EXECUTION.WRITE_SKIP_COUNT
     *
     * @mbg.generated
     */
    public void setWriteSkipCount(Long writeSkipCount) {
        this.writeSkipCount = writeSkipCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_STEP_EXECUTION.PROCESS_SKIP_COUNT
     *
     * @return the value of BATCH_STEP_EXECUTION.PROCESS_SKIP_COUNT
     *
     * @mbg.generated
     */
    public Long getProcessSkipCount() {
        return processSkipCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_STEP_EXECUTION.PROCESS_SKIP_COUNT
     *
     * @param processSkipCount the value for BATCH_STEP_EXECUTION.PROCESS_SKIP_COUNT
     *
     * @mbg.generated
     */
    public void setProcessSkipCount(Long processSkipCount) {
        this.processSkipCount = processSkipCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_STEP_EXECUTION.ROLLBACK_COUNT
     *
     * @return the value of BATCH_STEP_EXECUTION.ROLLBACK_COUNT
     *
     * @mbg.generated
     */
    public Long getRollbackCount() {
        return rollbackCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_STEP_EXECUTION.ROLLBACK_COUNT
     *
     * @param rollbackCount the value for BATCH_STEP_EXECUTION.ROLLBACK_COUNT
     *
     * @mbg.generated
     */
    public void setRollbackCount(Long rollbackCount) {
        this.rollbackCount = rollbackCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_STEP_EXECUTION.EXIT_CODE
     *
     * @return the value of BATCH_STEP_EXECUTION.EXIT_CODE
     *
     * @mbg.generated
     */
    public String getExitCode() {
        return exitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_STEP_EXECUTION.EXIT_CODE
     *
     * @param exitCode the value for BATCH_STEP_EXECUTION.EXIT_CODE
     *
     * @mbg.generated
     */
    public void setExitCode(String exitCode) {
        this.exitCode = exitCode == null ? null : exitCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_STEP_EXECUTION.EXIT_MESSAGE
     *
     * @return the value of BATCH_STEP_EXECUTION.EXIT_MESSAGE
     *
     * @mbg.generated
     */
    public String getExitMessage() {
        return exitMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_STEP_EXECUTION.EXIT_MESSAGE
     *
     * @param exitMessage the value for BATCH_STEP_EXECUTION.EXIT_MESSAGE
     *
     * @mbg.generated
     */
    public void setExitMessage(String exitMessage) {
        this.exitMessage = exitMessage == null ? null : exitMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_STEP_EXECUTION.LAST_UPDATED
     *
     * @return the value of BATCH_STEP_EXECUTION.LAST_UPDATED
     *
     * @mbg.generated
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_STEP_EXECUTION.LAST_UPDATED
     *
     * @param lastUpdated the value for BATCH_STEP_EXECUTION.LAST_UPDATED
     *
     * @mbg.generated
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }
}