package org.vincent.dao.model;

public class BatchJobInstance {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_JOB_INSTANCE.JOB_INSTANCE_ID
     *
     * @mbg.generated
     */
    private Long jobInstanceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_JOB_INSTANCE.VERSION
     *
     * @mbg.generated
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_JOB_INSTANCE.JOB_NAME
     *
     * @mbg.generated
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_JOB_INSTANCE.JOB_KEY
     *
     * @mbg.generated
     */
    private String jobKey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_JOB_INSTANCE.JOB_INSTANCE_ID
     *
     * @return the value of BATCH_JOB_INSTANCE.JOB_INSTANCE_ID
     *
     * @mbg.generated
     */
    public Long getJobInstanceId() {
        return jobInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_JOB_INSTANCE.JOB_INSTANCE_ID
     *
     * @param jobInstanceId the value for BATCH_JOB_INSTANCE.JOB_INSTANCE_ID
     *
     * @mbg.generated
     */
    public void setJobInstanceId(Long jobInstanceId) {
        this.jobInstanceId = jobInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_JOB_INSTANCE.VERSION
     *
     * @return the value of BATCH_JOB_INSTANCE.VERSION
     *
     * @mbg.generated
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_JOB_INSTANCE.VERSION
     *
     * @param version the value for BATCH_JOB_INSTANCE.VERSION
     *
     * @mbg.generated
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_JOB_INSTANCE.JOB_NAME
     *
     * @return the value of BATCH_JOB_INSTANCE.JOB_NAME
     *
     * @mbg.generated
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_JOB_INSTANCE.JOB_NAME
     *
     * @param jobName the value for BATCH_JOB_INSTANCE.JOB_NAME
     *
     * @mbg.generated
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_JOB_INSTANCE.JOB_KEY
     *
     * @return the value of BATCH_JOB_INSTANCE.JOB_KEY
     *
     * @mbg.generated
     */
    public String getJobKey() {
        return jobKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_JOB_INSTANCE.JOB_KEY
     *
     * @param jobKey the value for BATCH_JOB_INSTANCE.JOB_KEY
     *
     * @mbg.generated
     */
    public void setJobKey(String jobKey) {
        this.jobKey = jobKey == null ? null : jobKey.trim();
    }
}