package org.vincent.dao.model;

public class BatchJobExecutionContext {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_JOB_EXECUTION_CONTEXT.JOB_EXECUTION_ID
     *
     * @mbg.generated
     */
    private Long jobExecutionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_JOB_EXECUTION_CONTEXT.SHORT_CONTEXT
     *
     * @mbg.generated
     */
    private String shortContext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_JOB_EXECUTION_CONTEXT.SERIALIZED_CONTEXT
     *
     * @mbg.generated
     */
    private String serializedContext;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_JOB_EXECUTION_CONTEXT.JOB_EXECUTION_ID
     *
     * @return the value of BATCH_JOB_EXECUTION_CONTEXT.JOB_EXECUTION_ID
     *
     * @mbg.generated
     */
    public Long getJobExecutionId() {
        return jobExecutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_JOB_EXECUTION_CONTEXT.JOB_EXECUTION_ID
     *
     * @param jobExecutionId the value for BATCH_JOB_EXECUTION_CONTEXT.JOB_EXECUTION_ID
     *
     * @mbg.generated
     */
    public void setJobExecutionId(Long jobExecutionId) {
        this.jobExecutionId = jobExecutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_JOB_EXECUTION_CONTEXT.SHORT_CONTEXT
     *
     * @return the value of BATCH_JOB_EXECUTION_CONTEXT.SHORT_CONTEXT
     *
     * @mbg.generated
     */
    public String getShortContext() {
        return shortContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_JOB_EXECUTION_CONTEXT.SHORT_CONTEXT
     *
     * @param shortContext the value for BATCH_JOB_EXECUTION_CONTEXT.SHORT_CONTEXT
     *
     * @mbg.generated
     */
    public void setShortContext(String shortContext) {
        this.shortContext = shortContext == null ? null : shortContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_JOB_EXECUTION_CONTEXT.SERIALIZED_CONTEXT
     *
     * @return the value of BATCH_JOB_EXECUTION_CONTEXT.SERIALIZED_CONTEXT
     *
     * @mbg.generated
     */
    public String getSerializedContext() {
        return serializedContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_JOB_EXECUTION_CONTEXT.SERIALIZED_CONTEXT
     *
     * @param serializedContext the value for BATCH_JOB_EXECUTION_CONTEXT.SERIALIZED_CONTEXT
     *
     * @mbg.generated
     */
    public void setSerializedContext(String serializedContext) {
        this.serializedContext = serializedContext == null ? null : serializedContext.trim();
    }
}