package org.vincent.dao.model;

import java.util.Date;

public class BatchJobExecution {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_JOB_EXECUTION.JOB_EXECUTION_ID
     *
     * @mbg.generated
     */
    private Long jobExecutionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_JOB_EXECUTION.VERSION
     *
     * @mbg.generated
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_JOB_EXECUTION.JOB_INSTANCE_ID
     *
     * @mbg.generated
     */
    private Long jobInstanceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_JOB_EXECUTION.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_JOB_EXECUTION.START_TIME
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_JOB_EXECUTION.END_TIME
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_JOB_EXECUTION.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_JOB_EXECUTION.EXIT_CODE
     *
     * @mbg.generated
     */
    private String exitCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_JOB_EXECUTION.EXIT_MESSAGE
     *
     * @mbg.generated
     */
    private String exitMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_JOB_EXECUTION.LAST_UPDATED
     *
     * @mbg.generated
     */
    private Date lastUpdated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_JOB_EXECUTION.JOB_CONFIGURATION_LOCATION
     *
     * @mbg.generated
     */
    private String jobConfigurationLocation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_JOB_EXECUTION.JOB_EXECUTION_ID
     *
     * @return the value of BATCH_JOB_EXECUTION.JOB_EXECUTION_ID
     *
     * @mbg.generated
     */
    public Long getJobExecutionId() {
        return jobExecutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_JOB_EXECUTION.JOB_EXECUTION_ID
     *
     * @param jobExecutionId the value for BATCH_JOB_EXECUTION.JOB_EXECUTION_ID
     *
     * @mbg.generated
     */
    public void setJobExecutionId(Long jobExecutionId) {
        this.jobExecutionId = jobExecutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_JOB_EXECUTION.VERSION
     *
     * @return the value of BATCH_JOB_EXECUTION.VERSION
     *
     * @mbg.generated
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_JOB_EXECUTION.VERSION
     *
     * @param version the value for BATCH_JOB_EXECUTION.VERSION
     *
     * @mbg.generated
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_JOB_EXECUTION.JOB_INSTANCE_ID
     *
     * @return the value of BATCH_JOB_EXECUTION.JOB_INSTANCE_ID
     *
     * @mbg.generated
     */
    public Long getJobInstanceId() {
        return jobInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_JOB_EXECUTION.JOB_INSTANCE_ID
     *
     * @param jobInstanceId the value for BATCH_JOB_EXECUTION.JOB_INSTANCE_ID
     *
     * @mbg.generated
     */
    public void setJobInstanceId(Long jobInstanceId) {
        this.jobInstanceId = jobInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_JOB_EXECUTION.CREATE_TIME
     *
     * @return the value of BATCH_JOB_EXECUTION.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_JOB_EXECUTION.CREATE_TIME
     *
     * @param createTime the value for BATCH_JOB_EXECUTION.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_JOB_EXECUTION.START_TIME
     *
     * @return the value of BATCH_JOB_EXECUTION.START_TIME
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_JOB_EXECUTION.START_TIME
     *
     * @param startTime the value for BATCH_JOB_EXECUTION.START_TIME
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_JOB_EXECUTION.END_TIME
     *
     * @return the value of BATCH_JOB_EXECUTION.END_TIME
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_JOB_EXECUTION.END_TIME
     *
     * @param endTime the value for BATCH_JOB_EXECUTION.END_TIME
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_JOB_EXECUTION.STATUS
     *
     * @return the value of BATCH_JOB_EXECUTION.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_JOB_EXECUTION.STATUS
     *
     * @param status the value for BATCH_JOB_EXECUTION.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_JOB_EXECUTION.EXIT_CODE
     *
     * @return the value of BATCH_JOB_EXECUTION.EXIT_CODE
     *
     * @mbg.generated
     */
    public String getExitCode() {
        return exitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_JOB_EXECUTION.EXIT_CODE
     *
     * @param exitCode the value for BATCH_JOB_EXECUTION.EXIT_CODE
     *
     * @mbg.generated
     */
    public void setExitCode(String exitCode) {
        this.exitCode = exitCode == null ? null : exitCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_JOB_EXECUTION.EXIT_MESSAGE
     *
     * @return the value of BATCH_JOB_EXECUTION.EXIT_MESSAGE
     *
     * @mbg.generated
     */
    public String getExitMessage() {
        return exitMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_JOB_EXECUTION.EXIT_MESSAGE
     *
     * @param exitMessage the value for BATCH_JOB_EXECUTION.EXIT_MESSAGE
     *
     * @mbg.generated
     */
    public void setExitMessage(String exitMessage) {
        this.exitMessage = exitMessage == null ? null : exitMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_JOB_EXECUTION.LAST_UPDATED
     *
     * @return the value of BATCH_JOB_EXECUTION.LAST_UPDATED
     *
     * @mbg.generated
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_JOB_EXECUTION.LAST_UPDATED
     *
     * @param lastUpdated the value for BATCH_JOB_EXECUTION.LAST_UPDATED
     *
     * @mbg.generated
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_JOB_EXECUTION.JOB_CONFIGURATION_LOCATION
     *
     * @return the value of BATCH_JOB_EXECUTION.JOB_CONFIGURATION_LOCATION
     *
     * @mbg.generated
     */
    public String getJobConfigurationLocation() {
        return jobConfigurationLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_JOB_EXECUTION.JOB_CONFIGURATION_LOCATION
     *
     * @param jobConfigurationLocation the value for BATCH_JOB_EXECUTION.JOB_CONFIGURATION_LOCATION
     *
     * @mbg.generated
     */
    public void setJobConfigurationLocation(String jobConfigurationLocation) {
        this.jobConfigurationLocation = jobConfigurationLocation == null ? null : jobConfigurationLocation.trim();
    }
}