package org.vincent.dao.model;

public class BatchStepExecutionContext {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_STEP_EXECUTION_CONTEXT.STEP_EXECUTION_ID
     *
     * @mbg.generated
     */
    private Long stepExecutionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_STEP_EXECUTION_CONTEXT.SHORT_CONTEXT
     *
     * @mbg.generated
     */
    private String shortContext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BATCH_STEP_EXECUTION_CONTEXT.SERIALIZED_CONTEXT
     *
     * @mbg.generated
     */
    private String serializedContext;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_STEP_EXECUTION_CONTEXT.STEP_EXECUTION_ID
     *
     * @return the value of BATCH_STEP_EXECUTION_CONTEXT.STEP_EXECUTION_ID
     *
     * @mbg.generated
     */
    public Long getStepExecutionId() {
        return stepExecutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_STEP_EXECUTION_CONTEXT.STEP_EXECUTION_ID
     *
     * @param stepExecutionId the value for BATCH_STEP_EXECUTION_CONTEXT.STEP_EXECUTION_ID
     *
     * @mbg.generated
     */
    public void setStepExecutionId(Long stepExecutionId) {
        this.stepExecutionId = stepExecutionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_STEP_EXECUTION_CONTEXT.SHORT_CONTEXT
     *
     * @return the value of BATCH_STEP_EXECUTION_CONTEXT.SHORT_CONTEXT
     *
     * @mbg.generated
     */
    public String getShortContext() {
        return shortContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_STEP_EXECUTION_CONTEXT.SHORT_CONTEXT
     *
     * @param shortContext the value for BATCH_STEP_EXECUTION_CONTEXT.SHORT_CONTEXT
     *
     * @mbg.generated
     */
    public void setShortContext(String shortContext) {
        this.shortContext = shortContext == null ? null : shortContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BATCH_STEP_EXECUTION_CONTEXT.SERIALIZED_CONTEXT
     *
     * @return the value of BATCH_STEP_EXECUTION_CONTEXT.SERIALIZED_CONTEXT
     *
     * @mbg.generated
     */
    public String getSerializedContext() {
        return serializedContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BATCH_STEP_EXECUTION_CONTEXT.SERIALIZED_CONTEXT
     *
     * @param serializedContext the value for BATCH_STEP_EXECUTION_CONTEXT.SERIALIZED_CONTEXT
     *
     * @mbg.generated
     */
    public void setSerializedContext(String serializedContext) {
        this.serializedContext = serializedContext == null ? null : serializedContext.trim();
    }
}