package org.vincent.dao.model;

public class Test {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.bl
     *
     * @mbg.generated
     */
    private Boolean bl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.id
     *
     * @return the value of test.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.id
     *
     * @param id the value for test.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.bl
     *
     * @return the value of test.bl
     *
     * @mbg.generated
     */
    public Boolean getBl() {
        return bl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.bl
     *
     * @param bl the value for test.bl
     *
     * @mbg.generated
     */
    public void setBl(Boolean bl) {
        this.bl = bl;
    }
}